[package]
name = "cryptotest"
version = "0.1.0"
authors = ["shengli <shengli@zccp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
rand = "0.7"
log = "0.4"
log4rs = "0.8"
time = "0.1.42"